# fly.toml app configuration file generated for test-project-b on 2026-02-27T00:31:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-project-b'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile.production'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  APP_URL = 'https://test-project-b.fly.dev'
  CACHE_STORE = 'file'
  DB_CONNECTION = 'mysql'
  DB_PORT = '4000'
  LOG_CHANNEL = 'stderr'
  MYSQL_ATTR_SSL_CA = '/etc/ssl/certs/ca-certificates.crt'
  QUEUE_CONNECTION = 'sync'
  SESSION_DRIVER = 'cookie'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
